Enable building on Linux

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,13 +1,17 @@
 #!/bin/bash
 
-if [ -f "/c/Program Files/CMake/bin/cmake.exe" ]; then
-	BINOC_CMAKE_PATH="/c/Program Files/CMake/bin/cmake.exe"
-elif [ -f "/c/Program Files (x86)/CMake/bin/cmake.exe" ]; then
-	BINOC_CMAKE_PATH="/c/Program Files (x86)/CMake/bin/cmake.exe"	
+cd "$(dirname "$0")"
+export PATH="$(pwd -P)/utils:$PATH"
+
+if ! BINOC_CMAKE_PATH="$(which cmake 2>/dev/null)" && uname | grep -i 'msys|mingw'; then
+	if [ -f "/c/Program Files/CMake/bin/cmake.exe" ]; then
+		BINOC_CMAKE_PATH="/c/Program Files/CMake/bin/cmake.exe"
+	elif [ -f "/c/Program Files (x86)/CMake/bin/cmake.exe" ]; then
+		BINOC_CMAKE_PATH="/c/Program Files (x86)/CMake/bin/cmake.exe"
+	fi
 else
-	echo Building requires CMake as well as a few other tools. This script also only works on Windows so Linux users will have to do it manually.
-	echo This MAY be resolved in the future...
-	exit 1
+		echo "cmake not found."
+		exit 1
 fi
 
 if [ -d ./obj-dir ]; then
